# Generated by Django 6.0.1 on 2026-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='district',
            name='specialties',
            field=models.JSONField(default=list, help_text="e.g. ['Laksa Kedah', 'Paddy Fields']"),
        ),
    ]
