# Generated by Django 6.0.1 on 2026-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_district_description_district_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='paddy_status',
            field=models.CharField(choices=[('planting', 'Planting (Menanam)'), ('growing', 'Growing (Membesar)'), ('harvesting', 'Harvesting (Menuai)'), ('fallow', 'Fallow (Jerami/Rehat)')], default='growing', max_length=20),
        ),
    ]
