# Generated by Django 6.0.1 on 2026-01-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_district_paddy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. P009', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('parliament_lat', models.FloatField()),
                ('parliament_lng', models.FloatField()),
                ('mp_name', models.CharField(help_text='Member of Parliament name', max_length=200)),
                ('mp_party', models.CharField(help_text='e.g. PAS, PKR, UMNO', max_length=100)),
                ('mp_photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='place_photos/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='categories',
            field=models.JSONField(default=list, help_text="List of categories e.g. ['Nature', 'Food']"),
        ),
        migrations.AlterField(
            model_name='place',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='DUN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. N12', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('dun_lat', models.FloatField()),
                ('dun_lng', models.FloatField()),
                ('adun_name', models.CharField(help_text='ADUN name', max_length=200)),
                ('adun_party', models.CharField(help_text='e.g. PAS, PKR, UMNO', max_length=100)),
                ('adun_photo_url', models.URLField(blank=True, null=True)),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duns', to='api.parliament')),
            ],
        ),
    ]
